stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t revforce-app .

deploy:
  stage: deploy
  script:
    - docker stop revforce-app || true
    - docker rm revforce-app || true
    - docker run -d -p 8000:8000 -e DATABASE_URL="$DATABASE_URL" revforce-app
