stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest  # Use Docker image to run the build
  services:
    - name: docker:19.03.12-dind  # Docker-in-Docker service
      alias: docker  # Alias to ensure the runner can resolve "docker"
  script:
    - docker info  # This command ensures the connection to Docker is established
    - docker build -t revforce-app .
  only:
    - main
    - pipe-deploy

deploy:
  stage: deploy
  script:
    - docker stop revforce-app || true
    - docker rm revforce-app || true
    - docker run -d -p 8000:8000 -e DATABASE_URL="$DATABASE_URL" revforce-app
  only:
    - main
    - pipe-deploy
