"""Change chart metric from chart table to chart_source table

Revision ID: 17d803ff1b36
Revises: 
Create Date: 2025-05-27 18:59:03.557400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17d803ff1b36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_metrics', 'spend')
    op.add_column('chart_sources', sa.Column('metrics', sa.ARRAY(sa.Enum('ctr', 'click', 'impression', 'spend', name='chartmetric')), nullable=False))
    op.drop_column('charts', 'metric')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('metric', postgresql.ENUM('ctr', 'click', 'impression', 'spend', name='chartmetric'), autoincrement=False, nullable=False))
    op.drop_column('chart_sources', 'metrics')
    op.add_column('ad_metrics', sa.Column('spend', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
