"""add spend column to ad_metrics

Revision ID: 922255a06524
Revises: 
Create Date: 2025-05-21 21:32:05.456941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '922255a06524'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charts')
    op.drop_table('ads')
    op.drop_table('chart_sources')
    op.drop_table('campaigns')
    op.drop_table('ad_metrics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_metrics',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ad_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ctr', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device', postgresql.ENUM('mobile', 'desktop', 'tablet', 'other', name='devicetype'), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name='ad_metrics_ad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ad_metrics_pkey')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('remote_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('daily_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('monthly_budget', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['account_configs.id'], name='campaigns_integration_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='campaigns_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chart_sources',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chart_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source_table', postgresql.ENUM('campaign', 'ad', name='sourcetable'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['charts.id'], name='chart_sources_chart_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chart_sources_pkey')
    )
    op.create_table('ads',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('remote_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('integration_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='ads_campaign_id_fkey'),
    sa.ForeignKeyConstraint(['integration_id'], ['account_configs.id'], name='ads_integration_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ads_pkey')
    )
    op.create_table('charts',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('pizza', 'line', 'bar', 'horizontal_bar', 'grouped_bar', name='charttype'), autoincrement=False, nullable=False),
    sa.Column('metric', postgresql.ENUM('ctr', 'click', 'impression', 'spend', name='chartmetric'), autoincrement=False, nullable=False),
    sa.Column('period_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('granularity_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('segment', postgresql.ENUM('device', 'date', name='chartsegment'), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='charts_account_id_fkey'),
    sa.ForeignKeyConstraint(['granularity_id'], ['periods.id'], name='charts_granularity_id_fkey'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], name='charts_period_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='charts_pkey')
    )
    # ### end Alembic commands ###
