name: CI/CD Pipeline

on:
  push:
    branches: [ main, pipeline ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: revforceapi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/revforce-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Configure SSH Key
        run: |
          # Cria diretório .ssh e configura permissões
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          
          # Escreve a chave .pem
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 400 ~/.ssh/deploy_key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ec2-18-191-202-58.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/revforce-app:latest
            docker stop revforce-app || true
            docker rm revforce-app || true
            docker run -d \
              -p 80:8000 \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e OPENAI_KEY="${{ secrets.OPENAI_KEY }}" \
              --name revforce-app \
              --network revforce-net \
              ${{ secrets.DOCKERHUB_USERNAME }}/revforce-app:latest
            docker exec -it revforce-app alembic upgrade head || true
